# Generated by Django 4.1.13 on 2024-03-02 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddNews',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.CharField(default='', max_length=5000)),
                ('location', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAdd',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerVaultModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('phoneno', models.BigIntegerField(null=True)),
                ('emailid', models.EmailField(default='', max_length=254)),
                ('address', models.CharField(default='', max_length=400)),
                ('gender', models.CharField(default='', max_length=100)),
                ('role', models.CharField(default='', max_length=100)),
                ('job', models.CharField(default='', max_length=100)),
                ('location', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MessageModel',
            fields=[
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='workervault.workervaultmodel')),
                ('reciever_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='workervault.workervaultmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=400)),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workervault.workervaultmodel')),
            ],
        ),
    ]
