# Generated by Django 4.1.13 on 2024-01-29 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNews',
            fields=[
                ('newsid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.CharField(default='', max_length=250)),
                ('image', models.ImageField(default='', max_length=500, upload_to='')),
                ('location', models.CharField(default='', max_length=200)),
                ('content', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='AdminAdd',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
