# Generated by Django 4.1.13 on 2024-03-05 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0002_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='workervault.workervaultmodel'),
            preserve_default=False,
        ),
    ]
