# Generated by Django 4.1.13 on 2024-01-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0002_addnews_adminadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnews',
            name='image',
            field=models.CharField(default='', max_length=500),
        ),
    ]
