# Generated by Django 4.1.13 on 2024-02-14 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0003_alter_addnews_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addnews',
            name='image',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=400)),
                ('emailid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workervault.workervaultmodel')),
            ],
        ),
    ]
