# Generated by Django 4.1.13 on 2024-02-22 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0004_alter_addnews_image_contactus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='emailid',
            new_name='userid',
        ),
    ]
