# Generated by Django 4.1.13 on 2024-03-05 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0004_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(default=' ', max_length=100)),
                ('reciever_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciever_name', to='workervault.workervaultmodel')),
                ('sender_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_name', to='workervault.workervaultmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
