# Generated by Django 4.1.13 on 2024-02-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0005_rename_emailid_contactus_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='userid',
            new_name='emailid',
        ),
    ]
