# Generated by Django 4.1.13 on 2024-03-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workervault", "0006_chat_delete_messagemodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="file",
        ),
        migrations.AlterField(
            model_name="chat",
            name="text",
            field=models.CharField(default="", max_length=300),
        ),
    ]
