# Generated by Django 4.1.13 on 2024-02-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0007_rename_emailid_contactus_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='workervaultmodel',
            name='job',
            field=models.CharField(default='', max_length=100),
        ),
    ]
