# Generated by Django 4.1.13 on 2024-03-18 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("workervault", "0007_remove_chat_file_alter_chat_text"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="id",
        ),
        migrations.AddField(
            model_name="chat",
            name="chat_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="chat",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="receiver",
                to="workervault.workervaultmodel",
            ),
        ),
        migrations.AlterField(
            model_name="chat",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sender",
                to="workervault.workervaultmodel",
            ),
        ),
    ]
