# Generated by Django 4.1.13 on 2024-02-28 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0008_workervaultmodel_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSeekersModel',
            fields=[
                ('seekersid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('phone', models.BigIntegerField(null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('password', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
