# Generated by Django 4.1.13 on 2024-03-18 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "workervault",
            "0008_remove_chat_id_chat_chat_id_alter_chat_receiver_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="job_id",
        ),
    ]
