# Generated by Django 4.1.13 on 2024-02-29 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0009_serviceseekersmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.JSONField(default=list)),
                ('seekersid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workervault.serviceseekersmodel')),
                ('userid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='workervault.workervaultmodel')),
            ],
        ),
    ]
