# Generated by Django 4.1.13 on 2024-02-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workervault', '0011_chat_delete_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='workervaultmodel',
            name='role',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='workervault.workervaultmodel'),
        ),
        migrations.DeleteModel(
            name='ServiceSeekersModel',
        ),
    ]
